### ISSUE TITLE
Not enough fire power to pass wave 56

### ISSUE THREAD

**Issue by jkufner** [reloZid/android-anuto#33] opened 2016-07-19 23:35 UTC
Cannons are practically ineffective. Creeps simply stay alive and walk no matter what turrets are around. Even if there are "eaters" at the end to send them back to start, they don't die...

**Comment by wldpaul** [comment] 2016-07-22 09:32
There is an issue as a similar to this problem, when the star enemies (self-healing) are in great quantity and the end of the level contains enough teleporters, they go through the level continually and manage to self-heal more damage than can be inflicted with the most powerful weapons.  This results in a game that runs for an eternity.

**Comment by stefannagy** [comment] 2016-07-28 08:18
I passed wave 56 yesterday, but for wave 57 you need even more fire power…

It's no big problem to reach wave 56 (I always hit 'Next Wave' as soon as possible), but then suddenly everything changes: I have to wait until wave 55 is finished and then focus all fire power on one single wave. Before that I don't need any black holes at all, suddenly I need four of them.

**Comment by ctgcwiqc** [comment] 2016-08-10 22:20
My 10 year old hit wave 76 today and lost only because screen turned off and hand starts over.

**Comment by goldencut** [comment] 2016-08-16 19:49
wtf...you ppl have some other version or smth? I can't get past wave 11.. :/

**Comment by ctgcwiqc** [comment] 2016-08-16 23:37
It's easy once you figure out the right way to do it.  I max enhance 2 cheapest guns, then save enough money for first double barrel upgrade.  I do about 5 of those max enhanced, then start making the gatlin gun upgraded variety.  I sell the guns off that have enhancements so I can reclaim some of the upgrade cash prior to building and upgraded gun, if that makes sense.  Then you need to start adding a few lasers and then rockets.

**Comment by cptMikky** [comment] 2016-09-09 10:37
So I beat wave 70 the other night but wave 71 is a 56-deja-vu.

The strategy to beat wave 56 involves heavy tactics, mostly due to #10 but it is beatable. The problem is that this wave is completely different from the others and it's quite hard. But it's not a *challenging hard*, it's more like *frustrating hard*. It feels more like playing against the game itself rather than against the in-game enemies.

After beating wave 56 and 57, the strategy goes back to normal until wave 71, which is pretty much wave 56 on heavy steroids. And this time, there really isn't enough firepower to beat the wave. Between waves 56 and 70 I was only able to build 4 or 5 new missile turrets which just isn't enough - the first Star was under constant beating but its health never dropped below 50 %.

So either the cash reward  must be increased or (preferably) new enhancements or upgrades must be introduced to keep the game playable beyond wave 70.

**Comment by karloluiten** [comment] 2017-03-02 17:48
It would be nice if the stars would only heal themselves. I never managed to get past lvl 56...

**Comment by cptMikky** [comment] 2017-03-02 18:39
It would be enough for stars' heal effect not to stack and perhaps if stars couldn't heal each other. But it would still be **much** better to have more upgrades instead :)

**Comment by karloluiten** [comment] 2017-03-17 07:44
I managed to get further. This tactic might help you.
![Level 60](http://i.imgur.com/cahxfOa.jpg)

**Comment by kerrydondry** [comment] 2017-03-22 09:39
And here is another tactic:

![screenshot_20170312-023200](https://cloud.githubusercontent.com/assets/1792762/24191323/c66f7f8a-0eeb-11e7-9bf5-c62f1ba81531.jpg)

Got lost in Level 71 (accidentally closed the app...):

![screenshot_20170319-010429](https://cloud.githubusercontent.com/assets/1792762/24191328/cba0105a-0eeb-11e7-9e7e-44981f66f4b5.jpg)

Would be great to have a global highscore :)

**Comment by dex2000** [comment] 2017-03-22 12:03
And other ... :)

![viewer](https://cloud.githubusercontent.com/assets/5686458/24196907/cd001d14-0eff-11e7-87d8-cddae9d7bcd0.png)

**Comment by dex2000** [comment] 2017-03-22 20:55
Doh ;)
![viewer](https://cloud.githubusercontent.com/assets/5686458/24220331/29da517c-0f4a-11e7-92b8-fc38ca00f773.png)

**Comment by cptMikky** [comment] 2017-03-30 09:54
So I got to wave 71 again. This time I was able to kill a whole **one** star. After about 45 minutes of gameplay. Guess if I let the game play over night, wave 71 could be beaten after all :)

**Comment by dex2000** [comment] 2017-04-04 17:31
Level 2, wave 72 ... reboot smartphone :(
Last Screenshot:
![screenshot_20170404-101807](https://cloud.githubusercontent.com/assets/5686458/24670124/343fb878-196d-11e7-91fe-24d62e302d46.png)

**Comment by ranit8** [comment] 2017-04-04 18:18
Wave 100 is definitely impossible, isolated one single star from the rest after killing everything else, and couldnt inflict enough damage.
![screenshot_20170403-080839](https://cloud.githubusercontent.com/assets/9259786/24671997/b58da3b4-1949-11e7-9ace-d8aee50426c4.png)

Gave up.
![screenshot_20170403-093309](https://cloud.githubusercontent.com/assets/9259786/24672008/c12ca436-1949-11e7-872b-2ed9e7c0b73e.png)

**Comment by dex2000** [comment] 2017-04-04 18:57
@ranit8 wow! 
But: looks like isnt really problem of damage vs time  - you have not enough slower-towers.

**Comment by juliodcs** [comment] 2017-04-08 19:36
To my mind, stars are a very interesting enemy because it forces you to change your strategy. If stars couldn't heal other enemies, the strategy would always be the same: Use lots of slower-torres.

So isolating stars It is an strategy the player has to learn about.

The major problem I see is that even isolating starts, I need lots of time just to kill one of them. For example, on level ~75, I need about 2 minutes of many cannons just to finish one of the stars.

So perhaps a better idea could be to make them easier to kill once they are isolated.

For example:

1) Stars can heal other units, but cannot self-heal
2) Very reduced maximum life
3) Stars can heal other stars, but with less effectiveness. This is for still forcing the player to isolate stars but at the same make it easier to kill isolated small groups of stars (2 or 3)

**Comment by reloZid** [comment] 2018-09-24 15:10
Moving to #142.

**Closed by reloZid** 2018-09-24 15:10 UTC
Labels: balancing
