### ISSUE TITLE
Increasing Scroe after Game Over!

### ISSUE THREAD

**Issue by S-Gross** [reloZid/android-anuto#185] opened 2020-10-01 12:05 UTC
Hi,

i observed that the score is still increasing after i am "Game Over!".
Instead of directly starting a new game, i just switched to another app.  
After some time i entered the game again, still with the game over screen but with a higher score. 
I could repeat this a few times until i increased my score by nearly 1million until all mobs run through the maze. 

Cheers
Stephan

**Comment by reloZid** [comment] 2020-11-25 16:27
I could reproduce this when closing the app, not just switching. But this indeed not intended. Thanks for reporting.

**Comment by reloZid** [comment] 2021-03-08 10:33
Fixed in v0.7.

**Closed by reloZid** 2021-03-08 10:33 UTC
Labels: bug
