### ISSUE TITLE
Cheaper to sell and start again than to upgrade

### ISSUE THREAD

**Issue by mvdan** [reloZid/android-anuto#19] opened 2016-07-07 18:18 UTC
If you enhance a turret, its upgrade price remains the same. This means that if you want to upgrade a tower later, enhancing it now is as good as throwing away the credits. I assume this is intended.

This sort of makes sense, and makes the player think twice before spending money for the short term. Then again, I think the upgrade price should go down even if a little bit when enhancing. Since enhancing increases the sell price, sometimes it gets to a point where it's cheaper to sell a very enhanced turret and start from scratch with a number of upgrades instead of upgrading it directly.

What about reducing the upgrade cost at the same rate that the sell cost is increased? That would nullify this effect.

**Comment by mamins1376** [comment] 2016-07-09 21:33
I found a much bigger logical bug, no needs for enhancing. you can increase your money about 4k in each cycle!

to reproduce:
1- make sure that you have at least ~33k(1300+31.5k)
2- place a bomber(the one that costs 250) somewhere
3- upgrade it twice
4- sell it.
5- done!!!

with this simple hack, you can build something like this(credits is 52.4k):
![img_ _](https://cloud.githubusercontent.com/assets/10245985/16710407/10e8ddcc-4642-11e6-8e5e-530abe75309a.jpg)

**Comment by mvdan** [comment] 2016-07-09 21:38
If that's true, it should be reported as a separate issue like #7.

**Comment by mamins1376** [comment] 2016-07-09 21:41
because both of these are logical bugs about credits management, i decided to write that here and not to file another issue.

**Comment by mvdan** [comment] 2016-07-09 21:42
They're clearly separate issues with separate fixes, though. That pretty much means separate github issues. Yours is a bug, mine is an enhancement or minor bug at most.

**Comment by reloZid** [comment] 2016-07-10 09:16
I would appreciate a new issue too. Also make sure you are using the latest version of the game (v0.1-5). For me this bug is about balancing enhance/upgrade/sell cost.

**Comment by reloZid** [comment] 2018-09-24 15:12
Moving to #142.

**Closed by reloZid** 2018-09-24 15:12 UTC
Labels: balancing

**Comment by mmm4m5m** [comment] 2019-06-17 06:54
Why closed... I also find this useful and necessary.
It is also about speed. Here example:
The cheapest tower cost 100 credits and upgrade is 5600 credits.
Upgrade to level 2 - cost 50. To level 3 - 60 credits. Total 210 credits. Sell price is 207 credits. Upgrade is the same, not changed - 5600 credits.

BUT IF I first sell, buy new and upgrade it then the total cost will smaller: 207+100+5600 credits.
This could be improved if upgrade price is dynamic, if it is reduced: 5600-207+100=5493 credits.

Good reason for this change is when I buy new tower and I want to upgrade it. BUT I do mistake and click enhance (fat fingers, wrong button).
